{
 "title": "Dashboard de erros",
 "description": "Dashboard que exibe erros no preenchimento de issues dentro do Github.",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Quantidade de issues sem descrição",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT COUNT(*) AS total_issues_sem_descricao\r\nFROM lake.`issues`\r\nWHERE description IS NULL OR description = '' OR description = 'null';\r\n"
    }
   ]
  },
  {
   "title": "Quantidade de issues sem tipo",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT COUNT(*) AS total_issues_sem_tipo\r\nFROM lake.`issues`\r\nWHERE `original_type` IS NULL OR `original_type` = '';\r\n"
    }
   ]
  },
  {
   "title": "Quantidade de issues sem assignees",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT COUNT(*) AS total_issues_sem_assignees\r\nFROM lake.`issues`\r\nWHERE assignee_name IS NULL OR assignee_name = '';\r\n"
    }
   ]
  },
  {
   "title": "Issues sem descrição",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT \r\n    status AS \"Status\", \r\n    title AS \"Título\", \r\n    priority AS \"Prioridade\", \r\n    `original_type` AS \"Tipo\", \r\n    creator_name AS \"Autor\", \r\n    assignee_name AS \"Responsável\", \r\n    lead_time_minutes AS \"Tempo de Execução (Minutos)\", \r\n    url AS \"Link\", \r\n    resolution_date AS \"Data de Fechamento\", \r\n    created_date AS \"Data de Criação\", \r\n   updated_date AS \"Última Atualização\"\r\nFROM lake.`issues`\r\nWHERE description IS NULL OR description = '' or description = 'null';\r\n"
    }
   ]
  },
  {
   "title": "Issues sem tipo",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT \r\n    status AS \"Status\", \r\n    title AS \"Título\",\r\n    description AS \"Descrição\",\r\n    priority AS \"Prioridade\",\r\n    creator_name AS \"Autor\", \r\n    assignee_name AS \"Responsável\", \r\n    lead_time_minutes AS \"Tempo de Execução (Minutos)\", \r\n    url AS \"Link\", \r\n    resolution_date AS \"Data de Fechamento\", \r\n    created_date AS \"Data de Criação\", \r\n   updated_date AS \"Última Atualização\"\r\nFROM lake.`issues`\r\nWHERE `original_type` IS NULL OR `original_type` = '';\r\n"
    }
   ]
  },
  {
   "title": "Issues sem assignees",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT \r\n    status AS \"Status\", \r\n    title AS \"Título\",\r\n    description AS \"Descrição\",\r\n    priority AS \"Prioridade\", \r\n    `original_type` AS \"Tipo\", \r\n    creator_name AS \"Autor\",\r\n    lead_time_minutes AS \"Tempo de Execução (Minutos)\", \r\n    url AS \"Link\", \r\n    resolution_date AS \"Data de Fechamento\", \r\n    created_date AS \"Data de Criação\", \r\n   updated_date AS \"Última Atualização\"\r\nFROM lake.`issues`\r\nWHERE assignee_name IS NULL OR assignee_name = '';\r\n"
    }
   ]
  }
 ]
}