{
 "title": "SonarQube Server",
 "tags": [
  "Data Source Dashboard",
  "Stable Data Sources"
 ],
 "time": { "from": "now", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project_id",
    "label": "SonarQube Project",
    "query": "select concat(name, '--', id) as text from cq_projects"
   },
   {
    "name": "severity",
    "label": "Severity",
    "query": "select distinct severity from cq_issues where id like 'sonar%'"
   }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Introduction",
   "type": "text",
   "gridPos": { "h": 4, "w": 13, "x": 0, "y": 0 },
   "options": {
    "content": "- Use Cases: This dashboard shows the code quality metrics from SonarQube.\n- Data Source Required: SonarQube v8.2+\n- This dashboard does not honor the time filter on the top-right side as SonarQube metrics are all from the latest scan."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Reliability & Security",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Reliability",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bugs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT\r\n  count(distinct id) as 'Bugs'\r\nFROM cq_issues\r\nWHERE\r\n  project_key in (${project_id})\r\n  and type = 'BUG'\r\n  and severity in (${severity})"
    }
   ]
  },
  {
   "title": "Security",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "vulnerabilities" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT\r\n  count(distinct id) as 'Vulnerabilities'\r\nFROM cq_issues\r\nWHERE\r\n  project_key in (${project_id})\r\n  and type = 'VULNERABILITY'\r\n  and severity in (${severity})"
    }
   ]
  },
  {
   "title": "Security Hotspots",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "hotspots" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT\r\n  COUNT(distinct id) AS 'Security Hotspots'\r\nFROM cq_issues\r\nWHERE\r\n  project_key in (${project_id})\r\n  and type = 'HOTSPOTS'\r\n  and severity in (${severity})\r\n"
    }
   ]
  },
  {
   "title": "Security Reviewed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT\r\n  CONCAT(ROUND(COUNT(IF(status != 'TO_REVIEW', id, NULL)) / COUNT(distinct id) * 100, 2), '%') AS 'Reviewed'\r\nFROM cq_issues\r\nWHERE\r\n  project_key in (${project_id})\r\n  and type = 'HOTSPOTS'\r\n  and severity in (${severity})"
    }
   ]
  },
  {
   "title": "Test & Maintainability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Test",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT\r\n  CONCAT(ROUND((sum(lines_to_cover) - sum(uncovered_lines)) / sum(lines_to_cover) * 100, 1), '% ', 'Coverage on ', ROUND(sum(lines_to_cover) / 1000, 0),'k Lines to cover')\r\nFROM cq_file_metrics\r\nWHERE\r\n  project_key in (${project_id})\r\n"
    }
   ]
  },
  {
   "title": "Maintainability - Debt",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT\r\n  concat(FLOOR(SUM(debt)/8/60), \" day(s) \", FLOOR((SUM(debt)%480)/60), \" hour(s) \") AS 'Debt'\r\nFROM cq_issues\r\nWHERE\r\n  project_key in (${project_id})\r\n  and type = 'CODE_SMELL'\r\n  and severity in (${severity})\r\n  "
    }
   ]
  },
  {
   "title": "Maintainability - Code Smells",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "code smells" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT\r\n\tCOUNT(distinct id) as 'Code Smells'\r\nFROM cq_issues\r\nWHERE\r\n  project_key in (${project_id})\r\n  and type = 'CODE_SMELL'\r\n  and severity in (${severity})"
    }
   ]
  },
  {
   "title": "Duplication & Code",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Duplicated Blocks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT\r\n  sum(duplicated_blocks)\r\nFROM cq_file_metrics\r\nWHERE\r\n  project_key in (${project_id})\r\n"
    }
   ]
  },
  {
   "title": "Duplicated Lines",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT\r\n  CONCAT(ROUND(sum(duplicated_lines) / sum(num_of_lines) * 100, 1), '% ', 'Duplications on ', ROUND(sum(ncloc) / 1000, 0),'k Lines')\r\nFROM cq_file_metrics\r\nWHERE\r\n  project_key in (${project_id})\r\n"
    }
   ]
  },
  {
   "title": "Code Quality Metrics by Files (Top 20 order by Bugs)",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT\r\n\tfile_name, num_of_lines as 'Lines of Code', bugs as 'Bugs', vulnerabilities as 'Vulnerabilities', code_smells as 'Code Smells', \r\n\tsecurity_hotspots as 'Security Hotspots', CONCAT(ROUND(coverage, 2), '%') as 'Coverage', CONCAT(ROUND(duplicated_lines_density, 2), '%') as 'Duplications'\r\nFROM cq_file_metrics\r\nWHERE\r\n  project_key in (${project_id})\r\nORDER BY bugs desc\r\nlimit 20"
    }
   ]
  }
 ]
}